export const SAVE_EVENT_SUCCESSFUL = "SAVE_EVENT_SUCCESSFUL";
export const SAVE_EVENT_ERROR = "SAVE_EVENT_ERROR";

export const EDIT_EVENT_SUCCESSFUL = "EDIT_EVENT2_SUCCESSFUL";
export const EDIT_EVENT_ERROR = "EDIT_EVENT_ERROR";
